services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - web

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    depends_on:
      - nginx
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      DEFAULT_EMAIL: Zhandos30101@gmail.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - web

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "airline_system"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Maximum0004"
    ports:
      - "5432:5432"
    networks:
      - backend

  backend:
    image: 092446241709.dkr.ecr.eu-north-1.amazonaws.com/airline-system-backend:latest
    command: gunicorn airline_system.wsgi:application --bind 0.0.0.0:8000
    environment:
      DATABASE_URL: "postgres://postgres:Maximum0004@db:5432/airline_system"
      VIRTUAL_HOST: zydevlab.duckdns.org
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST: zydevlab.duckdns.org
      LETSENCRYPT_EMAIL: Zhandos30101@gmail.com
    depends_on:
      - db
    networks:
      - backend
      - web

  frontend:
    image: 092446241709.dkr.ecr.eu-north-1.amazonaws.com/airline-system-frontend:latest
    environment:
      VIRTUAL_HOST: www.zydevlab.duckdns.org
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: www.zydevlab.duckdns.org
      LETSENCRYPT_EMAIL: Zhandos30101@gmail.com
    depends_on:
      - backend
    networks:
      - web

volumes:
  postgres_data:

networks:
  backend:
  web:
