services:
  backend:
    image: 092446241709.dkr.ecr.eu-north-1.amazonaws.com/airline-system-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    image: 092446241709.dkr.ecr.eu-north-1.amazonaws.com/airline-system-frontend:latest
    ports:
      - "80:80"  # 👈 this is the correct mapping
    restart: always

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: airline
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
