# Generated by Django 5.1.7 on 2025-04-01 10:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
