# Generated by Django 5.1.7 on 2025-04-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_booking_booking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(max_length=100),
        ),
    ]
