# Generated by Django 5.1.7 on 2025-05-03 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
