# Generated by Django 5.1.7 on 2025-05-06 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
