name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-lates

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 092446241709.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build and push backend image
        run: |
          docker build -t 092446241709.dkr.ecr.eu-north-1.amazonaws.com/airline-system-backend:latest .
          docker push 092446241709.dkr.ecr.eu-north-1.amazonaws.com/airline-system-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -f ./final-back/my-frontend/Dockerfile -t 092446241709.dkr.ecr.eu-north-1.amazonaws.com/airline-system-frontend:latest ./final-back/my-frontend
          docker push 092446241709.dkr.ecr.eu-north-1.amazonaws.com/airline-system-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@51.20.34.116 << 'EOF'
            aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 092446241709.dkr.ecr.eu-north-1.amazonaws.com
            cd /home/ubuntu
            git pull origin master
            docker pull 092446241709.dkr.ecr.eu-north-1.amazonaws.com/airline-system-backend:latest
            docker pull 092446241709.dkr.ecr.eu-north-1.amazonaws.com/airline-system-frontend:latest
            docker-compose down
            docker-compose up -d
          EOF
