name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          region: eu-north-1  # Adjust region as needed
          aws-region: 'eu-north-1'

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 092446241709.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build and push backend image to ECR
        run: |
          docker build -t 092446241709.dkr.ecr.eu-north-1.amazonaws.com/airline-system-backend:latest .
          docker push 092446241709.dkr.ecr.eu-north-1.amazonaws.com/airline-system-backend:latest

      - name: Build and push frontend image to ECR
        run: |
          docker build -f ./final-back/my-frontend/Dockerfile -t 092446241709.dkr.ecr.eu-north-1.amazonaws.com/airline-system-frontend:latest ./final-back/my-frontend
          docker push 092446241709.dkr.ecr.eu-north-1.amazonaws.com/airline-system-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy backend to server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@51.20.34.116 '
            aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 092446241709.dkr.ecr.eu-north-1.amazonaws.com &&
            docker pull 092446241709.dkr.ecr.eu-north-1.amazonaws.com/airline-system-backend:latest &&
            docker-compose -f /home/ubuntu/docker-compose.yml up -d
          '

      - name: Deploy frontend to server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@51.20.34.116 'docker pull 092446241709.dkr.ecr.eu-north-1.amazonaws.com/airline-system-frontend:latest && docker-compose -f /home/ubuntu/docker-compose.yml up -d'